#!groovy
node {

    def err = null
    currentBuild.result = "SUCCESS"

    try {
       stage 'Checkout'
            checkout scm

       stage 'Deploy and Clean Database'
            echo 'Deployment'			
			sh 'int-gtkpkg-sp-catalogue/deployment.sh'
       
       stage 'Test: GK and Catalogues UP'
            echo 'GK and Catalogues UP'
            sh 'int-gtkpkg-sp-catalogue/tests.sh'

       stage 'Test1: POST Package'
            echo 'POST Package'
            sh 'int-gtkpkg-sp-catalogue/tests1.sh'
       
       stage 'Test2: GET Services'
            echo 'GET Services'
            sh 'int-gtkpkg-sp-catalogue/tests2.sh'
	   
       stage 'Test3: GET Functions'
            echo 'GET Functions'
            sh 'int-gtkpkg-sp-catalogue/tests3.sh'

       stage 'Notifications'
            echo 'Sending mails'

            mail body: 'project build successful',
                        from: 'sonata-nfv@gmail.com',
                        replyTo: 'sonata-nfv@gmail.com',
                        subject: 'project build successful',
                        to: 'dani.guija@i2cat.net', 'shuaib.siddiqui@i2cat.net, 'felipe.vicens@atos.net', 'jbonnet@alticelabs.com'
        }


    catch (caughtError) {
        err = caughtError
        currentBuild.result = "FAILURE"
            mail body: "project build error: ${err}" ,
            from: 'sonata-nfv@gmail.com',
            replyTo: 'sonata-nfv@gmail.com',
            subject: 'project build error',
            to: 'dani.guija@i2cat.net', 'shuaib.siddiqui@i2cat.net', 'felipe.vicens@atos.net', 'jbonnet@alticelabs.com'
        }

    finally {
        /* Must re-throw exception to propagate error */
        if (err) {
            throw err
        }

    }

}