#!groovy
node {

    def err = null
    currentBuild.result = "SUCCESS"

    try {
       stage 'Checkout'
            checkout scm

       stage 'Deploy'
            echo 'Push to int-server'			
			sh 'int-gtkpkg-sp-catalogue/deployment.sh'

       stage 'Testing'
            echo 'Testing Phase'
            sh 'int-gtkpkg-sp-catalogue/tests.sh'
			
       stage 'Notifications'
            echo 'Sending mails'

            mail body: 'project build successful',
                        from: 'sonata-nfv@gmail.com',
                        replyTo: 'sonata-nfv@gmail.com',
                        subject: 'project build successful',
                        to: 'dani.guija@i2cat.net', 'shuaib.siddiqui@i2cat.net, 'felipe.vicens@atos.net', 'jbonnet@alticelabs.com'
        }


    catch (caughtError) {
        err = caughtError
        currentBuild.result = "FAILURE"
            mail body: "project build error: ${err}" ,
            from: 'sonata-nfv@gmail.com',
            replyTo: 'sonata-nfv@gmail.com',
            subject: 'project build error',
            to: 'dani.guija@i2cat.net', 'shuaib.siddiqui@i2cat.net', 'felipe.vicens@atos.net', 'jbonnet@alticelabs.com'
        }

    finally {
        /* Must re-throw exception to propagate error */
        if (err) {
            throw err
        }

    }

}