#get admin logs
test_name: get_admin_logs

includes:
  - !include environment_file

stages:
  - name: get_logs
    request:
      url: "{logs_host:s}"
      method: GET
    response:
      status_code: 200