#get token
test_name: upload_packages

stages:
  - name: get_token
    request:
      url: http://sp.int3.sonata-nfv.eu:32001/api/v2/sessions
      json: 
        username: sonata
        password: '1234'
      method: POST
      headers:
        Content-Type: application/json
    response: 
      status_code: 200
      headers:
        content-type: application/json
      save:
        body:
          test_login_token: token.access_token

#upload packages
  - name: upload_packages
    request:
      url: http://sp.int3.sonata-nfv.eu:32001/api/v2/packages
      file: /media/sf_compartida/sonata-empty-service.son
      method: POST
      headers:
        content-type: application/json
        authorization: "Bearer {test_login_token:s}"
    response:
      status_code: 201
