#!groovy
node {

    def err = null
    currentBuild.result = "SUCCESS"

    try {
       stage 'Checkout'
            checkout scm
            

       stage 'Deploy'
            echo 'Install test Environment'
            sh 'int-mon/deploytestenv.sh'
       stage 'Test monitoring server'
            echo 'Check monitoring server'
            sh 'int-mon/tests/check_MON2DB_connection.sh'
       stage 'Test data collection from SP'
            echo 'Check data collection from SP'
            sh 'int-mon/tests/check_data_SP.sh'
       stage 'Test data collection from a TEST VNF'     
            echo 'Check data collection from TEST VNF'
            sh 'int-mon/tests/check_data_testVNF.sh'
       stage 'Test Prometheus reconfiguration'
            echo 'Check Prometheus reconfiguration (New Service)'
            sh 'int-mon/tests/check_newserv_conf.sh'
       stage 'Test Prometheus Alerts'
            echo 'Check connection between Prometheus and son-broker'
            sh 'int-mon/tests/check_MON2Mbroker_connection.sh'

       stage 'Notifications'
            echo 'Sending mails'

            mail body: 'MONITOR int test executed successfully',
                        from: 'sonata-nfv@gmail.com',
                        replyTo: 'sonata-nfv@gmail.com',
                        subject: 'MONITOR int test executed successfully',
                        to: 'pkarkazis@synelixis.com'
        }


    catch (caughtError) {
        err = caughtError
        currentBuild.result = "FAILURE"
            mail body: "MONITOR int test  error: ${err}" ,
            from: 'sonata-nfv@gmail.com',
            replyTo: 'sonata-nfv@gmail.com',
            subject: 'MONITOR project build error',
            to: 'pkarkazis@synelixis.com'
        }

    finally {
        /* Must re-throw exception to propagate error */
        if (err) {
            throw err
        }

    }

}
