#!groovy
node {

    def err = null
    currentBuild.result = "SUCCESS"

    try {
       stage 'Checkout'
            checkout scm

       stage 'Deploy'
            echo 'Install test Environment'			
	    sh 'int-gui/deploytestenv.sh'

       stage 'Test Server'
            echo 'Check Server'
            sh 'int-gui/tests/test_server.sh'
       stage 'Test Monitoring Endpoints'
            echo 'Check Monitoring Endpoints'
            sh 'int-gui/tests/test_monitoring_server.sh'
       stage 'Test GK Endpoints'
            echo 'Check GK Endpoints'
            sh 'int-gui/tests/test_gk_functions.sh'
            sh 'int-gui/tests/test_gk_packages.sh'
            sh 'int-gui/tests/test_gk_services.sh'

       stage 'Notifications'
            echo 'Sending mails'

            mail body: 'project build successful',
                        from: 'sonata-nfv@gmail.com',
                        replyTo: 'sonata-nfv@gmail.com',
                        subject: 'project build successful',
                        to: 'pkarkazis@synelixis.com'
        }


    catch (caughtError) {
        err = caughtError
        currentBuild.result = "FAILURE"
            mail body: "project build error: ${err}" ,
            from: 'sonata-nfv@gmail.com',
            replyTo: 'sonata-nfv@gmail.com',
            subject: 'project build error',
            to: 'pkarkazis@synelixis.com'
        }

    finally {
        /* Must re-throw exception to propagate error */
        if (err) {
            throw err
        }

    }

}
