#!groovy
node {

    def err = null
    currentBuild.result = "SUCCESS"

    try {
        stage('Checkout') {
            checkout scm
        }

        stage('Init') {
            echo 'Fetch and Start Service Containers'
            sh 'cd int-sdk-sonemu-examples && ./deployment.sh'
        }

    }

    catch (caughtError) {
        err = caughtError
        currentBuild.result = "FAILURE"
    }

    finally {
        sh 'docker rm -f son-emu-int-sdk-pipeline son-cli-int-test'
        /* Must re-throw exception to propagate error */
        if (err) {
            throw err
        }

    }
}