#!/bin/bash
set -e
set -x

# Wait until a line appears in the screen session.
# It starts from the beginning of the log and exits after the first match.
T=${2:-20s}
timeout -k 3s ${T} stdbuf -o0 grep -q -m 1 "^${1}" <(tail -F -n+0 screenlog.0)
