#!groovy
node {

    def err = null
    currentBuild.result = "SUCCESS"

    try {
       stage 'Checkout'
            checkout scm

       stage 'Deploy Containers'
            echo 'Fetch and Start Service Containers'
	        sh 'int-sdk/deployment.sh'

	   stage 'Clean Environment'
	        echo 'Clean dir structure, clean catalogue and prepare environment'
            sh "docker exec son-cli-int-test /bin/bash -c 'cd /tests; ./clean-environment.sh'"

       stage 'Test 01: Create Workspace [son-workspace --init]'
            echo 'Testing: Create workspace'
            sh "docker exec son-cli-int-test /bin/bash -c 'cd /tests; scripts/1_create_son_workspace.sh workspaces/ws1'"

       stage 'Test 02: Create Standalone Project [son-workspace --project]'
            echo 'Testing: Create sample project'
            sh "docker exec son-cli-int-test /bin/bash -c 'cd /tests; son-workspace --workspace workspaces/ws1 --project projects/prj_sample'"
            echo 'Testing: Create standalone project from template'
            sh "docker exec son-cli-int-test /bin/bash -c 'cd /tests; scripts/2_create_standalone-project.sh workspaces/ws1 projects/prj1 resources/project-Y1-emu.zip'"

       stage 'Test 03: Publish Project to SDK Catalogue [son-publish]'
            echo 'Testing: Publish project to SDK catalogue'
            sh "docker exec son-cli-int-test /bin/bash -c 'cd /tests; son-publish --workspace workspaces/ws1 --project projects/prj1'"

       stage 'Test 04: Create Dependent Project [son-workspace --project]'
            echo 'Testing: Create dependent project from template'
            sh "docker exec son-cli-int-test /bin/bash -c 'cd /tests; scripts/3_create_dependent-project.sh workspaces/ws1 projects/prj2 resources/project-Y1-emu.zip'"

       stage 'Test 05: Package Projects [son-package]'
            echo 'Testing: Package standalone project'
            sh "docker exec son-cli-int-test /bin/bash -c 'cd /tests; son-package --workspace workspaces/ws1 --project projects/prj1 -d packages/package.1.standalone -n sonata-demo-docker'"
            echo 'Testing: Package dependent project'
            sh "docker exec son-cli-int-test /bin/bash -c 'cd /tests; son-package --workspace workspaces/ws1 --project projects/prj2 -d packages/package.2.dependent -n sonata-demo-docker'"

       stage 'Test 06: Push Projects to emu GK [son-push]'
            echo 'Testing: Push package (project standalone) to emulator GK'
            sh "docker exec son-cli-int-test /bin/bash -c 'cd /tests; son-push -U packages/package.1.standalone/sonata-demo-docker.son http://127.0.0.1:5000'"
            echo 'Testing: Push package (project dependent) to emulator GK'
            sh "docker exec son-cli-int-test /bin/bash -c 'cd /tests; son-push -U packages/package.2.dependent/sonata-demo-docker.son http://127.0.0.1:5000'"

       stage 'Clean Environment'
            echo 'Clean dir structure, clean catalogue and prepare environment'
	        sh "docker exec son-cli-int-test /bin/bash -c 'cd /tests; ./clean-environment.sh'"



       stage 'Notifications'
            echo 'Sending mails'

            mail body: 'int-sdk-pipeline integration tests were successful',
                        from: 'sonata-nfv@gmail.com',
                        replyTo: 'sonata-nfv@gmail.com',
                        subject: 'int-sdk-pipeline: build successful',
                        to: 'lconceicao@ubiwhere.com'
        }

    catch (caughtError) {
        err = caughtError
        currentBuild.result = "FAILURE"
            mail body: "int-sdk-pipeline build error: ${err}" ,
            from: 'sonata-nfv@gmail.com',
            replyTo: 'sonata-nfv@gmail.com',
            subject: 'int-sdk-pipeline: build error',
            to: 'lconceicao@ubiwhere.com, tbatista@ubiwhere.com'
        }

    finally {
        /* Must re-throw exception to propagate error */
        if (err) {
            throw err
        }

    }
}